apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello
    tier: hello
  type: NodePort

---
apiVersion: apps/v1
kind: Pods
metadata:
  name: hello
  labels:
    app: hello
spec:
  spec:
      containers:
      - image: nginx
        name: hello
        ports:
        - containerPort: 80
          name: hello
